nameOverride: "devspaces"
fullnameOverride: ""

namespace: ""

aiAssistantModel: qwen3-235b

devEnvironments:
  startTimeoutSeconds: 300
  secondsOfRunBeforeIdling: -1
  secondsOfInactivityBeforeIdling: -1
  maxNumberOfWorkspacesPerUser: 5
  maxNumberOfRunningWorkspacesPerUser: 5
  defaultEditor: che-incubator/che-code/latest
  storage:
    pvc:
      pvcStrategy: per-workspace
  resources:
    limits:
      memory: 6Gi
      cpu: "4"
    requests:
      memory: 512Mi
      cpu: 500m

imagePuller:
  images:
    - name: project-clone
      image: registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:08c68ecad59b719c3e72c36a0dde0eff5c886d9d8d4024383677eab3db7c2220
    - name: udi-rhel9
      image: registry.redhat.io/devspaces/udi-rhel9:3.26.1
    - name: code-rhel9
      image: registry.redhat.io/devspaces/code-rhel9@sha256:5cd4fe568b4352bc5ef6ec0b16c3235fe515c2afb86fb076ed435cea65ea2247
    - name: traefik-rhel9
      image: registry.redhat.io/devspaces/traefik-rhel9@sha256:8aec0b9e11747bd2c0354abb6e75d4de32b1f0cf28477a8277254c0bc63d6019

openVSXURL: "https://open-vsx.org"

gitlab:
  host: ""

argocd:
  enabled: true
  instance:
    syncwave: "0"
