apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cekit-builder
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.git.contextDir }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: DockerImage
      name: {{ .Values.registry.hostname }}/{{ .Values.registry.namespace }}/{{ .Values.registry.builderImage }}:{{ .Values.registry.builderTag }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  resources: {}
  postCommit: {}