apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi9
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi9:9.8
    importPolicy:
      importMode: Legacy
    name: "9.8"
    referencePolicy:
      type: Source