kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-podman
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: cekit-builder
    namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-builder-podman