kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-podman
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - cekit-podman-builder