apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: cekit-podman-builder
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
allowHostPorts: false
priority: null
requiredDropCapabilities:
  - KILL
  - MKNOD
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
users: []
allowHostDirVolumePlugin: false
allowHostIPC: false
seLinuxContext:
  type: MustRunAs
readOnlyRootFilesystem: false
fsGroup:
  type: MustRunAs
groups: []
userNamespaceLevel: AllowHostLevel
defaultAddCapabilities: null
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowedCapabilities:
  - SETUID
  - SETGID
