---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: openvsx-extension-uploader
  labels:
    {{- include "openvsx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.git.uri }}
      ref: {{ .Values.build.git.ref }}
    contextDir: cluster/openvsx/extension-uploader
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: openvsx-extension-uploader:latest
  triggers:
    - type: ConfigChange
