---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openvsx-extension-uploader
  labels:
    {{- include "openvsx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
