---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-vsx-pg
  labels:
    {{- include "openvsx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  replicas: {{ .Values.postgresql.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: open-vsx-pg
  template:
    metadata:
      labels:
        name: open-vsx-pg
        {{- include "openvsx.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
                - /usr/libexec/check-container
          livenessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 120
            exec:
              command:
                - /usr/libexec/check-container
                - --live
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: open-vsx-pg
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: open-vsx-pg
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: open-vsx-pg
                  key: database-name
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: open-vsx-pg-data
              mountPath: /var/lib/pgsql/data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
      volumes:
        - name: open-vsx-pg-data
          persistentVolumeClaim:
            claimName: open-vsx-pg
      securityContext:
        seccompProfile:
          type: RuntimeDefault
