---
apiVersion: v1
kind: Service
metadata:
  name: open-vsx-pg
  labels:
    {{- include "openvsx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    name: open-vsx-pg
  type: ClusterIP
