---
apiVersion: v1
kind: Service
metadata:
  name: open-vsx-server
  labels:
    {{- include "openvsx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ports:
    - name: open-vsx-server
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    name: open-vsx-server
  type: ClusterIP
